#!/bin/sh

#
# chext
#
# Change the extension of a file.
#
# usage: chext foo.bar baz
# Moves foo.bar to foo.baz.
#

# Print to stderr (file descriptor 2)
perror()
{
	printf "%b" "$*" >&2;
}

# Print the usage message for this script
print_usage()
{
	perror "usage: $0 [-iv] file [file_2] [file_3] [...] extension\n"
}

# Process options
## Add each encountered option to $flags
flags=""
while getopts "iv" option; do
	case "$option" in
		i)
			flags="${flags}i"
			;;
		v)
			flags="${flags}v"
			;;
		*)
			;;
	esac
done
## If there were any options, prefix them with '-'
if [ -n "$flags" ]; then
	flags="-${flags}"
fi

# Shift the argument pointer past all options
shift $((OPTIND-1))
[ "$1" = "--" ] && shift

# Make sure that there exists at least one file and an extension
## Exit 2 if the passed arguments were insufficient
if [ $# -lt 2 ]; then
	print_usage
	exit 2
fi

# Get the extension as $ext
## Get the last argument (i.e., the extension)
for ext; do
	true
done
## If extension is not blank, start it with '.'
if [ -n "$ext" ]; then
	case $ext in
		.*)
			;;
		*)
			ext=.${ext}
			;;
	esac
fi
printf "%s\n" "ext = $ext"

# Change the extensions of the passed files
while [ $# -ge 2 ]; do
	errmsg_noext="$0: change extension of $1 to \"$ext\": $1 has no extension\n"
	errmsg_nofile="$0: change extension of $1 to \"$ext\": $1 does not exist\n"

	# Make sure that $1 exists
	if [ ! -e "$1" ]; then
		perror "$errmsg_nofile"
		shift
		continue
	fi

	# Extract $1's filename from its path
	filename="${1##*/}"

	# Make sure that $filename has '.' in it
	case "$filename" in
		*.*)
			;;
		*)
			perror "$errmsg_noext"
			shift
			continue
			;;
	esac

	# Make sure that $filename is not hidden with no extension
	if [ -z "${filename%\.*}" ]; then
		perror "$errmsg_noext"
		shift
		continue
	fi

	# Change $1's extension
	if [ -z "$flags" ]; then
		mv "$1" "${1%\.*}$ext"
	else
		mv "$flags" "$1" "${1%\.*}$ext"
	fi

	# Go to the next argument
	shift
done
