.TH CHEXT 1 "2016-05-25" "version 0.1" "General Commands Manual"

.SH NAME
.B chext
- A utility to easily change filename extensions.

.SH SYNOPSIS
.B chext
.RI [ options ]
.I file
.RI [ file_2 ]
.RI [ file_3 ]
.RI [ ... ]
.I extension

.SH DESCRIPTION
.B chext
is a simple shell utility for adding, removing, and changing filename extensions, where an extension is the last substring in a filename to begin with a period.

.B chext
accepts one or more files and a single extension as arguments.
Files may be specified individually or as regex.

.B mv
is used to perform the actual movement of files to their new filenames.
As such, the file arguments may be absolute paths, relative paths, or a mix of both absolute and relative paths.

File arguments without any current extension will have
.I extension
appended to them.

Removing extensions is done by passing
.I extension
as an empty string ("").

.SH OPTIONS
.TP
.B \-i interactive
Prompt the user for confirmation before renaming a file over an existing file.
.TP
.B -v verbose
Show the source and destination filenames as
.B chext
renames files.

.SH EXAMPLES
.nf
$ touch foo.bar
$ ls
foo.bar
$ chext foo.bar baz
$ ls
foo.baz
$ touch qux.baz
$ chext *.baz bar
$ ls
foo.bar  qux.bar
.fi

.SH ISC LICENSE
Copyright (c) 2016, Joseph LaFreniere <joseph@lafreniere.xyz>

Permission to use, copy, modify, and/or distribute this software for any purpose with or without fee is hereby granted, provided that the above copyright notice and this permission notice appear in all copies.

THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
